//! Render parsed manifests into Rust source: a single `MANIFESTS` array of typed
//! `AgentManifest` values. The output is `include!`-d into `crate::agent::manifest`,
//! so it references the `AgentManifest`, `AgentKind`, `SkillId`, `CapabilityName`,
//! and `RetryCount` types defined/imported there.
//!
//! Generation uses `quote` to build a typed `proc_macro2::TokenStream` rather
//! than hand-concatenating source strings, so string escaping, slice literals,
//! and integer suffixes are handled for us and the fragments are syntactically
//! checked.

use proc_macro2::TokenStream;
use quote::quote;

use crate::parse::ParsedManifest;

/// Render the full generated module body for `kinds` (assumed already sorted for
/// deterministic output): a single `pub const MANIFESTS: &[AgentManifest]`.
pub fn render(kinds: &[ParsedManifest]) -> String {
    let entries = kinds.iter().map(render_entry);

    let body = quote! {
        #[doc = "Every firmware-baked agent manifest, one entry per kind under `resources/agents/`."]
        pub const MANIFESTS: &[AgentManifest] = &[
            #(#entries),*
        ];
    };

    format!(
        "// @generated by claw_core/manifest_gen/ — do not edit by hand.\n\
         // Source: resources/agents/<kind>/ parsed at compile time.\n\n{body}\n"
    )
}

/// One `AgentManifest { ... }` array entry.
fn render_entry(kind: &ParsedManifest) -> TokenStream {
    let kind_name = &kind.kind;
    let description = &kind.description;
    let spawn_enabled = kind.spawn_enabled;
    let allowed_kinds = kind.allowed_kinds.iter();
    let retries = kind.retries;
    let tool_block_retries = match kind.tool_block_retries {
        Some(value) => quote! { ::core::option::Option::Some(RetryCount::new(#value)) },
        None => quote! { ::core::option::Option::None },
    };
    let capabilities = kind.capabilities.iter();
    let skills = kind.skills.iter();
    let instructions = kind
        .instructions_path
        .to_str()
        .expect("instructions.md path is valid UTF-8");

    quote! {
        AgentManifest {
            kind: AgentKind::from_static(#kind_name),
            description: #description,
            spawn_enabled: #spawn_enabled,
            allowed_kinds: &[#(AgentKind::from_static(#allowed_kinds)),*],
            retries: RetryCount::new(#retries),
            tool_block_retries: #tool_block_retries,
            capabilities: &[#(CapabilityName::new(#capabilities)),*],
            skills: &[#(SkillId::from_static(#skills)),*],
            instructions: include_str!(#instructions),
        }
    }
}
