use core::any::{type_name, TypeId};
use core::future::Future;
use core::marker::PhantomData;
use core::mem::align_of;
use core::pin::Pin;
use core::task::{Context, Poll};

use futures_core::Stream;
use getset::{CopyGetters, Getters};
use zerocopy::{Immutable, IntoBytes, KnownLayout, TryFromBytes};

use super::frame::{write_frame, write_method_error_frame, FramedReader, OutcomeReader, RpcFrame};
use super::lane::{LaneReader, LaneWriter, LANE_FRAME_ALIGNMENT};
use super::registry::{ErasedRpcHandler, PreparedCall, RpcFuture};
use super::{RpcAddress, RpcContext, RpcError, RpcResult};

mod private {
    pub trait Sealed {}
}

/// A fixed-layout value that may be viewed directly in a typed RPC frame.
///
/// Deriving [`TryFromBytes`], [`IntoBytes`], [`KnownLayout`], and [`Immutable`]
/// rejects pointers and uninitialized padding at compile time. Message types
/// should use an explicit representation and explicit byte-order fields for a
/// stable wire format.
pub trait RpcMessage: TryFromBytes + IntoBytes + KnownLayout + Immutable + 'static {}

impl<T> RpcMessage for T where T: TryFromBytes + IntoBytes + KnownLayout + Immutable + 'static {}

/// Whether one side of a typed method carries one message or a message stream.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RpcCardinality {
    /// Exactly one typed message.
    Unary,
    /// Zero or more typed messages until EOF.
    Streaming,
}

/// Marker selecting exactly one typed message.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Unary;

/// Marker selecting zero or more typed messages.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Streaming;

impl private::Sealed for Unary {}
impl private::Sealed for Streaming {}

/// A task-local stream whose outer [`RpcResult`] reports transport failures.
pub struct RpcStream<T> {
    inner: Pin<Box<dyn Stream<Item = RpcResult<T>> + 'static>>,
}

impl<T> RpcStream<T> {
    /// Boxes a typed message stream for use as RPC input or output.
    #[must_use]
    pub fn new<S>(stream: S) -> Self
    where
        S: Stream<Item = RpcResult<T>> + 'static,
    {
        Self {
            inner: Box::pin(stream),
        }
    }

    /// Waits for the next stream item.
    ///
    /// `None` means that the peer closed this direction normally.
    pub async fn next(&mut self) -> Option<RpcResult<T>> {
        core::future::poll_fn(|context| Pin::new(&mut *self).poll_next(context)).await
    }
}

impl<T> Unpin for RpcStream<T> {}

impl<T> Stream for RpcStream<T> {
    type Item = RpcResult<T>;

    fn poll_next(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.get_mut().inner.as_mut().poll_next(context)
    }
}

/// Compile-time description of one typed RPC method.
///
/// Implementations are normally generated by a service macro. They may also be
/// written manually for small services and tests.
pub trait RpcMethod: 'static {
    /// Stable runtime address in `group.method` form.
    const ADDRESS: &'static str;

    /// Message carried from caller to handler.
    type Request: RpcMessage;

    /// Message carried from handler to caller.
    type Response: RpcMessage;

    /// Method-specific error carried from handler to caller.
    type Error: RpcMessage;

    /// Request-side cardinality.
    type Input: RpcInputMode<Self::Request>;

    /// Response-side cardinality.
    type Output: RpcOutputMode<Self::Response, Self::Error>;
}

/// Runtime descriptor used to reject client/handler mismatches before IO.
#[derive(Clone, CopyGetters, Debug, Getters, PartialEq, Eq)]
pub(crate) struct RpcMethodDescriptor {
    #[getset(get = "pub(crate)")]
    address: RpcAddress,
    method_type_id: TypeId,
    #[getset(get_copy = "pub(crate)")]
    method_type_name: &'static str,
    request_type_id: TypeId,
    request_type_name: &'static str,
    response_type_id: TypeId,
    response_type_name: &'static str,
    error_type_id: TypeId,
    error_type_name: &'static str,
    input_cardinality: RpcCardinality,
    output_cardinality: RpcCardinality,
}

impl RpcMethodDescriptor {
    pub(crate) fn for_method<M>() -> RpcResult<Self>
    where
        M: RpcMethod,
    {
        const {
            assert!(
                align_of::<M::Request>() <= LANE_FRAME_ALIGNMENT,
                "RPC request message alignment exceeds lane frame alignment"
            );
            assert!(
                align_of::<M::Response>() <= LANE_FRAME_ALIGNMENT,
                "RPC response message alignment exceeds lane frame alignment"
            );
            assert!(
                align_of::<M::Error>() <= LANE_FRAME_ALIGNMENT,
                "RPC method error alignment exceeds lane frame alignment"
            );
        }
        let address = RpcAddress::try_from(M::ADDRESS)?;
        Ok(Self {
            address,
            method_type_id: TypeId::of::<M>(),
            method_type_name: type_name::<M>(),
            request_type_id: TypeId::of::<M::Request>(),
            request_type_name: type_name::<M::Request>(),
            response_type_id: TypeId::of::<M::Response>(),
            response_type_name: type_name::<M::Response>(),
            error_type_id: TypeId::of::<M::Error>(),
            error_type_name: type_name::<M::Error>(),
            input_cardinality: M::Input::CARDINALITY,
            output_cardinality: M::Output::CARDINALITY,
        })
    }
}

struct ActiveCall {
    input: RpcFuture<'static>,
    handler: RpcFuture<'static>,
    response: LaneReader,
}

type SetupFuture = Pin<Box<dyn Future<Output = RpcResult<ActiveCall>> + 'static>>;

pub(crate) struct RpcCallSetup {
    future: SetupFuture,
}

pub(crate) fn setup_call<M>(
    prepared: PreparedCall,
    input: <M::Input as RpcInputMode<M::Request>>::ClientInput,
) -> RpcCallSetup
where
    M: RpcMethod,
{
    let input = M::Input::into_stream(input);
    RpcCallSetup {
        future: Box::pin(async move {
            let mut acquired = prepared.acquire().await?;
            let lane = acquired.take_lane()?;
            let input = encode_stream(input, lane.request_writer);
            let handler = acquired.start(lane.request_reader, lane.response_writer);
            Ok(ActiveCall {
                input,
                handler,
                response: lane.response_reader,
            })
        }),
    }
}

/// Boxed task-local future returned by a handler implementation.
pub type RpcHandlerFuture<'a, T> = Pin<Box<dyn Future<Output = RpcResult<T>> + 'a>>;

/// Input type received by a handler for method `M`.
pub type RpcHandlerInput<M> =
    <<M as RpcMethod>::Input as RpcInputMode<<M as RpcMethod>::Request>>::HandlerInput;

/// Typed business output returned by a handler for method `M`.
///
/// Unary output is `Result<Response, Error>`. Streaming output is a stream of
/// those outcomes; a method error terminates the encoded response stream.
pub type RpcHandlerOutput<M> = <<M as RpcMethod>::Output as RpcOutputMode<
    <M as RpcMethod>::Response,
    <M as RpcMethod>::Error,
>>::HandlerOutput;

/// Business-logic implementation for one [`RpcMethod`].
pub trait RpcHandler<M>
where
    M: RpcMethod,
{
    /// Handles one request frame or request-frame stream.
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: RpcHandlerInput<M>,
    ) -> RpcHandlerFuture<'a, RpcHandlerOutput<M>>;
}

impl<M, H, Fut> RpcHandler<M> for H
where
    M: RpcMethod,
    H: Fn(RpcContext, RpcHandlerInput<M>) -> Fut,
    Fut: Future<Output = RpcResult<RpcHandlerOutput<M>>> + 'static,
{
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: RpcHandlerInput<M>,
    ) -> RpcHandlerFuture<'a, RpcHandlerOutput<M>> {
        Box::pin((self)(context, input))
    }
}

/// Type-level request cardinality behavior.
///
/// This trait is sealed; use [`Unary`] or [`Streaming`].
pub trait RpcInputMode<T>: private::Sealed
where
    T: RpcMessage,
{
    /// Value accepted by [`RpcClient::call`](crate::rpc::RpcClient::call).
    type ClientInput;

    /// Value delivered to [`RpcHandler`].
    type HandlerInput;

    /// Runtime cardinality value.
    const CARDINALITY: RpcCardinality;

    #[doc(hidden)]
    fn into_stream(input: Self::ClientInput) -> RpcStream<T>;

    #[doc(hidden)]
    fn decode_stream(
        input: RpcStream<RpcFrame<T>>,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput>;
}

/// Type-level typed-result and response-cardinality behavior.
///
/// This trait is sealed; use [`Unary`] or [`Streaming`].
pub trait RpcOutputMode<T, E>: private::Sealed
where
    T: RpcMessage,
    E: RpcMessage,
{
    /// Typed `Result<Response, Error>` value or stream returned by a handler.
    type HandlerOutput;

    /// Self-driving call returned by [`RpcClient::call`](crate::rpc::RpcClient::call).
    type ClientCall;

    /// Runtime cardinality value.
    const CARDINALITY: RpcCardinality;

    #[doc(hidden)]
    fn into_stream(output: Self::HandlerOutput) -> RpcStream<Result<T, E>>;

    #[doc(hidden)]
    fn make_client_call(responses: RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>)
        -> Self::ClientCall;
}

impl<T> RpcInputMode<T> for Unary
where
    T: RpcMessage,
{
    type ClientInput = T;
    type HandlerInput = RpcFrame<T>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Unary;

    fn into_stream(input: Self::ClientInput) -> RpcStream<T> {
        RpcStream::new(OnceStream::new(input))
    }

    fn decode_stream(
        mut input: RpcStream<RpcFrame<T>>,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput> {
        Box::pin(async move { input.next().await.ok_or(RpcError::MissingUnaryFrame)? })
    }
}

impl<T> RpcInputMode<T> for Streaming
where
    T: RpcMessage,
{
    type ClientInput = RpcStream<T>;
    type HandlerInput = RpcStream<RpcFrame<T>>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Streaming;

    fn into_stream(input: Self::ClientInput) -> RpcStream<T> {
        input
    }

    fn decode_stream(
        input: RpcStream<RpcFrame<T>>,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput> {
        Box::pin(async move { Ok(input) })
    }
}

impl<T, E> RpcOutputMode<T, E> for Unary
where
    T: RpcMessage,
    E: RpcMessage,
{
    type HandlerOutput = Result<T, E>;
    type ClientCall = RpcUnaryCall<T, E>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Unary;

    fn into_stream(output: Self::HandlerOutput) -> RpcStream<Result<T, E>> {
        RpcStream::new(OnceStream::new(output))
    }

    fn make_client_call(
        responses: RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>,
    ) -> Self::ClientCall {
        RpcUnaryCall::new(responses)
    }
}

impl<T, E> RpcOutputMode<T, E> for Streaming
where
    T: RpcMessage,
    E: RpcMessage,
{
    type HandlerOutput = RpcStream<Result<T, E>>;
    type ClientCall = RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Streaming;

    fn into_stream(output: Self::HandlerOutput) -> RpcStream<Result<T, E>> {
        output
    }

    fn make_client_call(
        responses: RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>,
    ) -> Self::ClientCall {
        responses
    }
}

struct OnceStream<T> {
    value: Option<T>,
}

impl<T> OnceStream<T> {
    fn new(value: T) -> Self {
        Self { value: Some(value) }
    }
}

impl<T> Unpin for OnceStream<T> {}

impl<T> Stream for OnceStream<T> {
    type Item = RpcResult<T>;

    fn poll_next(self: Pin<&mut Self>, _context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        Poll::Ready(self.get_mut().value.take().map(Ok))
    }
}

fn encode_stream<T>(mut messages: RpcStream<T>, mut writer: LaneWriter) -> RpcFuture<'static>
where
    T: RpcMessage,
{
    Box::pin(async move {
        while let Some(message) = messages.next().await {
            write_frame(&mut writer, &message?).await?;
        }
        writer.close();
        Ok(())
    })
}

fn encode_outcome_stream<T, E>(
    mut outcomes: RpcStream<Result<T, E>>,
    mut writer: LaneWriter,
) -> RpcFuture<'static>
where
    T: RpcMessage,
    E: RpcMessage,
{
    Box::pin(async move {
        while let Some(outcome) = outcomes.next().await {
            match outcome? {
                Ok(message) => write_frame(&mut writer, &message).await?,
                Err(error) => {
                    write_method_error_frame(&mut writer, &error).await?;
                    break;
                }
            }
        }
        writer.close();
        Ok(())
    })
}

pub(crate) struct HandlerAdapter<M, H> {
    handler: H,
    method: PhantomData<fn() -> M>,
}

impl<M, H> HandlerAdapter<M, H> {
    pub(crate) fn new(handler: H) -> Self {
        Self {
            handler,
            method: PhantomData,
        }
    }
}

impl<M, H> ErasedRpcHandler for HandlerAdapter<M, H>
where
    M: RpcMethod,
    H: RpcHandler<M>,
{
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: LaneReader,
        output: LaneWriter,
    ) -> RpcFuture<'a> {
        Box::pin(async move {
            let input = RpcStream::new(FramedReader::new(input));
            let input = M::Input::decode_stream(input).await?;
            let output_value = self.handler.call(context, input).await?;
            encode_outcome_stream(M::Output::into_stream(output_value), output).await
        })
    }
}

struct CallDriver {
    setup: Option<SetupFuture>,
    input: Option<RpcFuture<'static>>,
    handler: Option<RpcFuture<'static>>,
}

enum CallProgress {
    Response(LaneReader),
    Complete,
}

impl CallDriver {
    fn new(setup: RpcCallSetup) -> Self {
        Self {
            setup: Some(setup.future),
            input: None,
            handler: None,
        }
    }

    fn poll_call(&mut self, context: &mut Context<'_>) -> Poll<RpcResult<CallProgress>> {
        if let Some(setup) = self.setup.as_mut() {
            match setup.as_mut().poll(context) {
                Poll::Ready(Ok(active)) => {
                    self.setup = None;
                    self.input = Some(active.input);
                    self.handler = Some(active.handler);
                    context.waker().wake_by_ref();
                    return Poll::Ready(Ok(CallProgress::Response(active.response)));
                }
                Poll::Ready(Err(error)) => {
                    self.setup = None;
                    return Poll::Ready(Err(error));
                }
                Poll::Pending => return Poll::Pending,
            }
        }

        let Some(handler) = self.handler.as_mut() else {
            return Poll::Ready(Ok(CallProgress::Complete));
        };
        match handler.as_mut().poll(context) {
            Poll::Ready(result) => {
                self.handler = None;
                self.input = None;
                return Poll::Ready(result.map(|()| CallProgress::Complete));
            }
            Poll::Pending => {}
        }

        let Some(input) = self.input.as_mut() else {
            return Poll::Pending;
        };
        match input.as_mut().poll(context) {
            Poll::Ready(Ok(())) => self.input = None,
            Poll::Ready(Err(error)) => {
                self.input = None;
                self.handler = None;
                return Poll::Ready(Err(error));
            }
            Poll::Pending => {}
        }
        Poll::Pending
    }
}

/// Self-driving unary typed RPC returned by [`RpcClient::call`](crate::rpc::RpcClient::call).
///
/// Polling this future concurrently advances request encoding, handler work,
/// and response decoding. Its outer [`RpcResult`] reports transport/runtime
/// failures; its inner `Result` contains either a zero-copy response frame or
/// the method's zero-copy typed error frame. No separate call task is required.
#[must_use = "futures do nothing unless polled or awaited"]
pub struct RpcUnaryCall<T, E> {
    responses: RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>,
    finished: bool,
}

impl<T, E> RpcUnaryCall<T, E> {
    fn new(responses: RpcStream<Result<RpcFrame<T>, RpcFrame<E>>>) -> Self {
        Self {
            responses,
            finished: false,
        }
    }
}

impl<T, E> Unpin for RpcUnaryCall<T, E> {}

impl<T, E> Future for RpcUnaryCall<T, E>
where
    T: RpcMessage,
    E: RpcMessage,
{
    type Output = RpcResult<Result<RpcFrame<T>, RpcFrame<E>>>;

    fn poll(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Self::Output> {
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(Err(RpcError::CompletedCallPolled));
        }

        match Pin::new(&mut this.responses).poll_next(context) {
            Poll::Ready(Some(result)) => {
                this.finished = true;
                Poll::Ready(result)
            }
            Poll::Ready(None) => {
                this.finished = true;
                Poll::Ready(Err(RpcError::MissingUnaryFrame))
            }
            Poll::Pending => Poll::Pending,
        }
    }
}

pub(crate) fn make_client_call<M>(
    setup: RpcCallSetup,
) -> <M::Output as RpcOutputMode<M::Response, M::Error>>::ClientCall
where
    M: RpcMethod,
{
    let responses = RpcStream::new(RpcResponseDriverStream::<M::Response, M::Error>::new(setup));
    M::Output::make_client_call(responses)
}

struct RpcResponseDriverStream<T, E> {
    driver: CallDriver,
    response: Option<OutcomeReader<T, E>>,
    response_eof: bool,
    driver_done: bool,
    finished: bool,
}

impl<T, E> RpcResponseDriverStream<T, E> {
    fn new(setup: RpcCallSetup) -> Self {
        Self {
            driver: CallDriver::new(setup),
            response: None,
            response_eof: false,
            driver_done: false,
            finished: false,
        }
    }
}

impl<T, E> Unpin for RpcResponseDriverStream<T, E> {}

impl<T, E> Stream for RpcResponseDriverStream<T, E>
where
    T: RpcMessage,
    E: RpcMessage,
{
    type Item = RpcResult<Result<RpcFrame<T>, RpcFrame<E>>>;

    fn poll_next(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }

        if !this.driver_done {
            match this.driver.poll_call(context) {
                Poll::Ready(Ok(CallProgress::Response(reader))) => {
                    this.response = Some(OutcomeReader::new(reader));
                }
                Poll::Ready(Ok(CallProgress::Complete)) => this.driver_done = true,
                Poll::Ready(Err(error)) => {
                    this.finished = true;
                    return Poll::Ready(Some(Err(error)));
                }
                Poll::Pending => {}
            }
        }

        if !this.response_eof {
            if let Some(response) = this.response.as_mut() {
                match Pin::new(response).poll_next(context) {
                    Poll::Ready(Some(item)) => return Poll::Ready(Some(item)),
                    Poll::Ready(None) => this.response_eof = true,
                    Poll::Pending => {}
                }
            }
        }

        if this.driver_done && this.response_eof {
            this.finished = true;
            return Poll::Ready(None);
        }
        Poll::Pending
    }
}
