use core::any::{type_name, TypeId};
use core::future::Future;
use core::marker::PhantomData;
use core::pin::Pin;
use core::task::{Context, Poll};

use futures_core::Stream;
use zerocopy::{Immutable, IntoBytes, KnownLayout, TryFromBytes};

use super::frame::{decode_unary, write_frame, FramedReader, RpcFrame};
use super::io::{close, BoxBinaryReader, BoxBinaryWriter};
use super::lane::LANE_FRAME_ALIGNMENT;
use super::registry::PreparedCall;
use super::{RawRpcProvider, RpcAddress, RpcContext, RpcError, RpcFuture, RpcResult};

const DEFAULT_FRAME_LIMIT: usize = 4_096;

mod private {
    pub trait Sealed {}
}

/// A fixed-layout value that may be viewed directly in a typed RPC frame.
///
/// Deriving [`TryFromBytes`], [`IntoBytes`], [`KnownLayout`], and [`Immutable`]
/// rejects pointers and uninitialized padding at compile time. Message types
/// should use an explicit representation and explicit byte-order fields for a
/// stable wire format.
pub trait RpcMessage: TryFromBytes + IntoBytes + KnownLayout + Immutable + 'static {}

impl<T> RpcMessage for T where T: TryFromBytes + IntoBytes + KnownLayout + Immutable + 'static {}

/// Whether one side of a typed method carries one message or a message stream.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RpcCardinality {
    /// Exactly one typed message.
    Unary,
    /// Zero or more typed messages until EOF.
    Streaming,
}

/// Marker selecting exactly one typed message.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Unary;

/// Marker selecting zero or more typed messages.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct Streaming;

impl private::Sealed for Unary {}
impl private::Sealed for Streaming {}

/// A task-local stream of RPC values or lane-backed frame views.
pub struct RpcStream<T> {
    inner: Pin<Box<dyn Stream<Item = RpcResult<T>> + 'static>>,
}

impl<T> RpcStream<T> {
    /// Boxes a typed message stream for use as RPC input or output.
    #[must_use]
    pub fn new<S>(stream: S) -> Self
    where
        S: Stream<Item = RpcResult<T>> + 'static,
    {
        Self {
            inner: Box::pin(stream),
        }
    }

    /// Waits for the next stream item.
    ///
    /// `None` means that the peer closed this direction normally.
    pub async fn next(&mut self) -> Option<RpcResult<T>> {
        core::future::poll_fn(|context| Pin::new(&mut *self).poll_next(context)).await
    }
}

impl<T> Unpin for RpcStream<T> {}

impl<T> Stream for RpcStream<T> {
    type Item = RpcResult<T>;

    fn poll_next(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.get_mut().inner.as_mut().poll_next(context)
    }
}

/// Compile-time description of one typed RPC method.
///
/// Implementations are normally generated by a service macro. They may also be
/// written manually for small services and tests.
pub trait RpcMethod: 'static {
    /// Stable runtime address in `group.method` form.
    const ADDRESS: &'static str;

    /// Message carried from caller to provider.
    type Request: RpcMessage;

    /// Message carried from provider to caller.
    type Response: RpcMessage;

    /// Request-side cardinality.
    type Input: RpcInputMode<Self::Request>;

    /// Response-side cardinality.
    type Output: RpcOutputMode<Self::Response>;

    /// Maximum encoded request frame size. Defaults to 4096 bytes.
    const MAX_REQUEST_FRAME: usize = DEFAULT_FRAME_LIMIT;

    /// Maximum encoded response frame size. Defaults to 4096 bytes.
    const MAX_RESPONSE_FRAME: usize = DEFAULT_FRAME_LIMIT;
}

/// Runtime descriptor used to reject typed client/provider mismatches before IO.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RpcMethodDescriptor {
    address: RpcAddress,
    method_type_id: TypeId,
    method_type_name: &'static str,
    request_type_id: TypeId,
    request_type_name: &'static str,
    response_type_id: TypeId,
    response_type_name: &'static str,
    input: RpcCardinality,
    output: RpcCardinality,
    max_request_frame: usize,
    max_response_frame: usize,
}

impl RpcMethodDescriptor {
    pub(crate) fn for_method<M>() -> RpcResult<Self>
    where
        M: RpcMethod,
    {
        let address = RpcAddress::parse(M::ADDRESS)?;
        if M::MAX_REQUEST_FRAME == 0 {
            return Err(RpcError::InvalidMethodConfiguration {
                address,
                field: "MAX_REQUEST_FRAME",
            });
        }
        if M::MAX_RESPONSE_FRAME == 0 {
            return Err(RpcError::InvalidMethodConfiguration {
                address,
                field: "MAX_RESPONSE_FRAME",
            });
        }
        validate_message_alignment::<M::Request>()?;
        validate_message_alignment::<M::Response>()?;
        Ok(Self {
            address,
            method_type_id: TypeId::of::<M>(),
            method_type_name: type_name::<M>(),
            request_type_id: TypeId::of::<M::Request>(),
            request_type_name: type_name::<M::Request>(),
            response_type_id: TypeId::of::<M::Response>(),
            response_type_name: type_name::<M::Response>(),
            input: M::Input::CARDINALITY,
            output: M::Output::CARDINALITY,
            max_request_frame: M::MAX_REQUEST_FRAME,
            max_response_frame: M::MAX_RESPONSE_FRAME,
        })
    }

    /// Returns the registered method address.
    #[must_use]
    pub fn address(&self) -> &RpcAddress {
        &self.address
    }

    /// Returns the Rust method marker name.
    #[must_use]
    pub fn method_type_name(&self) -> &'static str {
        self.method_type_name
    }

    /// Returns the Rust request type name.
    #[must_use]
    pub fn request_type_name(&self) -> &'static str {
        self.request_type_name
    }

    /// Returns the Rust response type name.
    #[must_use]
    pub fn response_type_name(&self) -> &'static str {
        self.response_type_name
    }

    /// Returns the request cardinality.
    #[must_use]
    pub fn input_cardinality(&self) -> RpcCardinality {
        self.input
    }

    /// Returns the response cardinality.
    #[must_use]
    pub fn output_cardinality(&self) -> RpcCardinality {
        self.output
    }

    /// Returns the maximum encoded request frame size.
    #[must_use]
    pub fn max_request_frame(&self) -> usize {
        self.max_request_frame
    }

    /// Returns the maximum encoded response frame size.
    #[must_use]
    pub fn max_response_frame(&self) -> usize {
        self.max_response_frame
    }
}

fn validate_message_alignment<T>() -> RpcResult<()>
where
    T: RpcMessage,
{
    let required = align_of::<T>();
    if required > LANE_FRAME_ALIGNMENT {
        return Err(RpcError::MessageAlignmentExceedsLane {
            message_type: type_name::<T>(),
            required,
            available: LANE_FRAME_ALIGNMENT,
        });
    }
    Ok(())
}

struct ActiveCall {
    input: RpcFuture<'static>,
    provider: RpcFuture<'static>,
    response: BoxBinaryReader,
}

type SetupFuture = Pin<Box<dyn Future<Output = RpcResult<ActiveCall>> + 'static>>;

/// Deferred acquisition and initialization of one fixed RPC lane.
///
/// This type is an implementation detail exposed only so the sealed
/// [`RpcOutputMode`] trait can construct its self-driving client value.
#[doc(hidden)]
pub struct RpcCallSetup {
    future: SetupFuture,
}

pub(crate) fn setup_call<M>(
    prepared: PreparedCall,
    input: <M::Input as RpcInputMode<M::Request>>::ClientInput,
) -> RpcCallSetup
where
    M: RpcMethod,
{
    RpcCallSetup {
        future: Box::pin(async move {
            let mut acquired = prepared.acquire().await?;
            let lane = acquired.take_lane()?;
            let input = M::Input::encode_input(input, lane.request_writer, M::MAX_REQUEST_FRAME);
            let provider = acquired.start(lane.request_reader, lane.response_writer);
            Ok(ActiveCall {
                input,
                provider,
                response: lane.response_reader,
            })
        }),
    }
}

/// Boxed task-local future returned by a typed provider implementation.
pub type RpcHandlerFuture<'a, T> = Pin<Box<dyn Future<Output = RpcResult<T>> + 'a>>;

/// Input type received by a handler for method `M`.
pub type RpcHandlerInput<M> =
    <<M as RpcMethod>::Input as RpcInputMode<<M as RpcMethod>::Request>>::HandlerInput;

/// Output type returned by a handler for method `M`.
pub type RpcHandlerOutput<M> =
    <<M as RpcMethod>::Output as RpcOutputMode<<M as RpcMethod>::Response>>::HandlerOutput;

/// Typed business-logic implementation for one [`RpcMethod`].
pub trait TypedRpcHandler<M>
where
    M: RpcMethod,
{
    /// Handles one request frame or request-frame stream.
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: RpcHandlerInput<M>,
    ) -> RpcHandlerFuture<'a, RpcHandlerOutput<M>>;
}

impl<M, H, Fut> TypedRpcHandler<M> for H
where
    M: RpcMethod,
    H: Fn(RpcContext, RpcHandlerInput<M>) -> Fut,
    Fut: Future<Output = RpcResult<RpcHandlerOutput<M>>> + 'static,
{
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: RpcHandlerInput<M>,
    ) -> RpcHandlerFuture<'a, RpcHandlerOutput<M>> {
        Box::pin((self)(context, input))
    }
}

/// Type-level request cardinality behavior.
///
/// This trait is sealed; use [`Unary`] or [`Streaming`].
pub trait RpcInputMode<T>: private::Sealed
where
    T: RpcMessage,
{
    /// Value accepted by [`RpcClient::call`](crate::rpc::RpcClient::call).
    type ClientInput;

    /// Value delivered to [`TypedRpcHandler`].
    type HandlerInput;

    /// Runtime cardinality value.
    const CARDINALITY: RpcCardinality;

    #[doc(hidden)]
    fn encode_input(
        input: Self::ClientInput,
        writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static>;

    #[doc(hidden)]
    fn decode_input(
        reader: BoxBinaryReader,
        limit: usize,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput>;
}

/// Type-level response cardinality behavior.
///
/// This trait is sealed; use [`Unary`] or [`Streaming`].
pub trait RpcOutputMode<T>: private::Sealed
where
    T: RpcMessage,
{
    /// Value returned by [`TypedRpcHandler`].
    type HandlerOutput;

    /// Self-driving call returned by [`RpcClient::call`](crate::rpc::RpcClient::call).
    type ClientCall;

    /// Runtime cardinality value.
    const CARDINALITY: RpcCardinality;

    #[doc(hidden)]
    fn encode_output(
        output: Self::HandlerOutput,
        writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static>;

    #[doc(hidden)]
    fn make_client_call(setup: RpcCallSetup, limit: usize) -> Self::ClientCall;
}

impl<T> RpcInputMode<T> for Unary
where
    T: RpcMessage,
{
    type ClientInput = T;
    type HandlerInput = RpcFrame<T>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Unary;

    fn encode_input(
        input: Self::ClientInput,
        mut writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static> {
        Box::pin(async move {
            write_frame(&mut writer, &input, limit).await?;
            close(writer.as_mut()).await?;
            Ok(())
        })
    }

    fn decode_input(
        reader: BoxBinaryReader,
        limit: usize,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput> {
        Box::pin(decode_unary(reader, limit))
    }
}

impl<T> RpcInputMode<T> for Streaming
where
    T: RpcMessage,
{
    type ClientInput = RpcStream<T>;
    type HandlerInput = RpcStream<RpcFrame<T>>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Streaming;

    fn encode_input(
        mut input: Self::ClientInput,
        mut writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static> {
        Box::pin(async move {
            while let Some(message) = input.next().await {
                write_frame(&mut writer, &message?, limit).await?;
            }
            close(writer.as_mut()).await?;
            Ok(())
        })
    }

    fn decode_input(
        reader: BoxBinaryReader,
        limit: usize,
    ) -> RpcHandlerFuture<'static, Self::HandlerInput> {
        Box::pin(async move { Ok(RpcStream::new(FramedReader::<T>::new(reader, limit))) })
    }
}

impl<T> RpcOutputMode<T> for Unary
where
    T: RpcMessage,
{
    type HandlerOutput = T;
    type ClientCall = RpcUnaryCall<T>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Unary;

    fn encode_output(
        output: Self::HandlerOutput,
        mut writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static> {
        Box::pin(async move {
            write_frame(&mut writer, &output, limit).await?;
            close(writer.as_mut()).await?;
            Ok(())
        })
    }

    fn make_client_call(setup: RpcCallSetup, limit: usize) -> Self::ClientCall {
        RpcUnaryCall::new(setup, limit)
    }
}

impl<T> RpcOutputMode<T> for Streaming
where
    T: RpcMessage,
{
    type HandlerOutput = RpcStream<T>;
    type ClientCall = RpcStream<RpcFrame<T>>;

    const CARDINALITY: RpcCardinality = RpcCardinality::Streaming;

    fn encode_output(
        mut output: Self::HandlerOutput,
        mut writer: BoxBinaryWriter,
        limit: usize,
    ) -> RpcFuture<'static> {
        Box::pin(async move {
            while let Some(message) = output.next().await {
                write_frame(&mut writer, &message?, limit).await?;
            }
            close(writer.as_mut()).await?;
            Ok(())
        })
    }

    fn make_client_call(setup: RpcCallSetup, limit: usize) -> Self::ClientCall {
        RpcStream::new(RpcResponseDriverStream::new(setup, limit))
    }
}

pub(crate) struct TypedProvider<M, H> {
    handler: H,
    method: PhantomData<fn() -> M>,
}

impl<M, H> TypedProvider<M, H> {
    pub(crate) fn new(handler: H) -> Self {
        Self {
            handler,
            method: PhantomData,
        }
    }
}

impl<M, H> RawRpcProvider for TypedProvider<M, H>
where
    M: RpcMethod,
    H: TypedRpcHandler<M>,
{
    fn call<'a>(
        &'a self,
        context: RpcContext,
        input: BoxBinaryReader,
        output: BoxBinaryWriter,
    ) -> RpcFuture<'a> {
        Box::pin(async move {
            let input = M::Input::decode_input(input, M::MAX_REQUEST_FRAME).await?;
            let output_value = self.handler.call(context, input).await?;
            M::Output::encode_output(output_value, output, M::MAX_RESPONSE_FRAME).await
        })
    }
}

struct CallDriver {
    setup: Option<SetupFuture>,
    input: Option<RpcFuture<'static>>,
    provider: Option<RpcFuture<'static>>,
}

enum CallProgress {
    Response(BoxBinaryReader),
    Complete,
}

impl CallDriver {
    fn new(setup: RpcCallSetup) -> Self {
        Self {
            setup: Some(setup.future),
            input: None,
            provider: None,
        }
    }

    fn poll_call(&mut self, context: &mut Context<'_>) -> Poll<RpcResult<CallProgress>> {
        if let Some(setup) = self.setup.as_mut() {
            match setup.as_mut().poll(context) {
                Poll::Ready(Ok(active)) => {
                    self.setup = None;
                    self.input = Some(active.input);
                    self.provider = Some(active.provider);
                    context.waker().wake_by_ref();
                    return Poll::Ready(Ok(CallProgress::Response(active.response)));
                }
                Poll::Ready(Err(error)) => {
                    self.setup = None;
                    return Poll::Ready(Err(error));
                }
                Poll::Pending => return Poll::Pending,
            }
        }

        let Some(provider) = self.provider.as_mut() else {
            return Poll::Ready(Ok(CallProgress::Complete));
        };
        match provider.as_mut().poll(context) {
            Poll::Ready(result) => {
                self.provider = None;
                self.input = None;
                return Poll::Ready(result.map(|()| CallProgress::Complete));
            }
            Poll::Pending => {}
        }

        let Some(input) = self.input.as_mut() else {
            return Poll::Pending;
        };
        match input.as_mut().poll(context) {
            Poll::Ready(Ok(())) => self.input = None,
            Poll::Ready(Err(error)) => {
                self.input = None;
                self.provider = None;
                return Poll::Ready(Err(error));
            }
            Poll::Pending => {}
        }
        Poll::Pending
    }
}

/// Self-driving unary typed RPC returned by [`RpcClient::call`](crate::rpc::RpcClient::call).
///
/// Polling this future concurrently advances request encoding, provider work,
/// and response decoding. No separate raw call task is required.
#[must_use = "futures do nothing unless polled or awaited"]
pub struct RpcUnaryCall<T> {
    driver: CallDriver,
    response: Option<FramedReader<T>>,
    response_limit: usize,
    value: Option<RpcFrame<T>>,
    response_eof: bool,
    driver_done: bool,
    finished: bool,
}

impl<T> RpcUnaryCall<T> {
    fn new(setup: RpcCallSetup, limit: usize) -> Self {
        Self {
            driver: CallDriver::new(setup),
            response: None,
            response_limit: limit,
            value: None,
            response_eof: false,
            driver_done: false,
            finished: false,
        }
    }

    fn fail(&mut self, error: RpcError) -> Poll<RpcResult<RpcFrame<T>>> {
        self.finished = true;
        Poll::Ready(Err(error))
    }
}

impl<T> Unpin for RpcUnaryCall<T> {}

impl<T> Future for RpcUnaryCall<T>
where
    T: RpcMessage,
{
    type Output = RpcResult<RpcFrame<T>>;

    fn poll(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Self::Output> {
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(Err(RpcError::CompletedCallPolled));
        }

        if !this.driver_done {
            match this.driver.poll_call(context) {
                Poll::Ready(Ok(CallProgress::Response(reader))) => {
                    this.response = Some(FramedReader::new(reader, this.response_limit));
                }
                Poll::Ready(Ok(CallProgress::Complete)) => this.driver_done = true,
                Poll::Ready(Err(error)) => return this.fail(error),
                Poll::Pending => {}
            }
        }

        if !this.response_eof {
            if let Some(response) = this.response.as_mut() {
                match Pin::new(response).poll_next(context) {
                    Poll::Ready(Some(Ok(value))) if this.value.is_none() => {
                        if value.is_borrowed() {
                            this.response_eof = true;
                        }
                        this.value = Some(value);
                        context.waker().wake_by_ref();
                    }
                    Poll::Ready(Some(Ok(_))) => return this.fail(RpcError::ExtraUnaryFrame),
                    Poll::Ready(Some(Err(error))) => return this.fail(error),
                    Poll::Ready(None) => this.response_eof = true,
                    Poll::Pending => {}
                }
            }
        }

        if this.driver_done && this.response_eof {
            this.finished = true;
            return Poll::Ready(this.value.take().ok_or(RpcError::MissingUnaryFrame));
        }
        Poll::Pending
    }
}

struct RpcResponseDriverStream<T> {
    driver: CallDriver,
    response: Option<FramedReader<T>>,
    response_limit: usize,
    response_eof: bool,
    driver_done: bool,
    finished: bool,
}

impl<T> RpcResponseDriverStream<T> {
    fn new(setup: RpcCallSetup, limit: usize) -> Self {
        Self {
            driver: CallDriver::new(setup),
            response: None,
            response_limit: limit,
            response_eof: false,
            driver_done: false,
            finished: false,
        }
    }
}

impl<T> Unpin for RpcResponseDriverStream<T> {}

impl<T> Stream for RpcResponseDriverStream<T>
where
    T: RpcMessage,
{
    type Item = RpcResult<RpcFrame<T>>;

    fn poll_next(self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }

        if !this.driver_done {
            match this.driver.poll_call(context) {
                Poll::Ready(Ok(CallProgress::Response(reader))) => {
                    this.response = Some(FramedReader::new(reader, this.response_limit));
                }
                Poll::Ready(Ok(CallProgress::Complete)) => this.driver_done = true,
                Poll::Ready(Err(error)) => {
                    this.finished = true;
                    return Poll::Ready(Some(Err(error)));
                }
                Poll::Pending => {}
            }
        }

        if !this.response_eof {
            if let Some(response) = this.response.as_mut() {
                match Pin::new(response).poll_next(context) {
                    Poll::Ready(Some(item)) => return Poll::Ready(Some(item)),
                    Poll::Ready(None) => this.response_eof = true,
                    Poll::Pending => {}
                }
            }
        }

        if this.driver_done && this.response_eof {
            this.finished = true;
            return Poll::Ready(None);
        }
        Poll::Pending
    }
}
